<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="12" total="20" passed="6" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-12T10:57:04 IST" name="PetStoreAutomationSuite" finished-at="2025-09-12T10:57:25 IST" duration-ms="21059">
    <groups>
      <group name="smoke">
        <method signature="UserTests.testCreateUser()[pri:0, instance:api.test.UserTests@3514a4c0]" name="testCreateUser" class="api.test.UserTests"/>
        <method signature="UserTests.testDeleteUser()[pri:0, instance:api.test.UserTests@3514a4c0]" name="testDeleteUser" class="api.test.UserTests"/>
        <method signature="UserTests2.testCreateMultipleUsers()[pri:0, instance:api.test.UserTests2@212b5695]" name="testCreateMultipleUsers" class="api.test.UserTests2"/>
        <method signature="UserTests2.testDeleteUser()[pri:0, instance:api.test.UserTests2@212b5695]" name="testDeleteUser" class="api.test.UserTests2"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="UserTests.testGetUserByName()[pri:0, instance:api.test.UserTests@209da20d]" name="testGetUserByName" class="api.test.UserTests"/>
        <method signature="UserTests.testUpdateUser()[pri:0, instance:api.test.UserTests@209da20d]" name="testUpdateUser" class="api.test.UserTests"/>
        <method signature="UserTests2.testGetAllUsers()[pri:0, instance:api.test.UserTests2@e15b7e8]" name="testGetAllUsers" class="api.test.UserTests2"/>
        <method signature="UserTests2.testUpdateUser()[pri:0, instance:api.test.UserTests2@e15b7e8]" name="testUpdateUser" class="api.test.UserTests2"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2025-09-12T10:57:04 IST" name="Smoke Test Execution" finished-at="2025-09-12T10:57:16 IST" duration-ms="11692">
      <class name="api.test.UserTests2">
        <test-method signature="testCreateMultipleUsers()[pri:0, instance:api.test.UserTests2@212b5695]" started-at="2025-09-12T10:57:11 IST" name="testCreateMultipleUsers" finished-at="2025-09-12T10:57:13 IST" duration-ms="2393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateMultipleUsers -->
        <test-method signature="testDeleteUser()[pri:0, instance:api.test.UserTests2@212b5695]" started-at="2025-09-12T10:57:13 IST" name="testDeleteUser" finished-at="2025-09-12T10:57:16 IST" duration-ms="2641" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to delete user! expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to delete user! expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at api.test.UserTests2.testDeleteUser(UserTests2.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUser -->
      </class> <!-- api.test.UserTests2 -->
      <class name="api.test.UserTests">
        <test-method signature="testCreateUser()[pri:0, instance:api.test.UserTests@3514a4c0]" started-at="2025-09-12T10:57:05 IST" name="testCreateUser" finished-at="2025-09-12T10:57:08 IST" duration-ms="3579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateUser -->
        <test-method signature="testDeleteUser()[pri:0, instance:api.test.UserTests@3514a4c0]" started-at="2025-09-12T10:57:08 IST" name="testDeleteUser" finished-at="2025-09-12T10:57:11 IST" duration-ms="2696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUser -->
      </class> <!-- api.test.UserTests -->
    </test> <!-- Smoke Test Execution -->
    <test started-at="2025-09-12T10:57:16 IST" name="Sanity Test Execution" finished-at="2025-09-12T10:57:25 IST" duration-ms="9076">
      <class name="api.test.UserTests2">
        <test-method signature="testGetAllUsers()[pri:0, instance:api.test.UserTests2@e15b7e8]" started-at="2025-09-12T10:57:21 IST" name="testGetAllUsers" finished-at="2025-09-12T10:57:23 IST" duration-ms="2262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAllUsers -->
        <test-method signature="testUpdateUser()[pri:0, instance:api.test.UserTests2@e15b7e8]" started-at="2025-09-12T10:57:23 IST" name="testUpdateUser" finished-at="2025-09-12T10:57:25 IST" duration-ms="2677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUser -->
      </class> <!-- api.test.UserTests2 -->
      <class name="api.test.UserTests">
        <test-method signature="testGetUserByName()[pri:0, instance:api.test.UserTests@209da20d]" started-at="2025-09-12T10:57:16 IST" name="testGetUserByName" finished-at="2025-09-12T10:57:19 IST" duration-ms="2270" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not found after creation! expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not found after creation! expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at api.test.UserTests.testGetUserByName(UserTests.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserByName -->
        <test-method signature="testUpdateUser()[pri:0, instance:api.test.UserTests@209da20d]" started-at="2025-09-12T10:57:19 IST" name="testUpdateUser" finished-at="2025-09-12T10:57:21 IST" duration-ms="1855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUser -->
      </class> <!-- api.test.UserTests -->
    </test> <!-- Sanity Test Execution -->
  </suite> <!-- PetStoreAutomationSuite -->
</testng-results>
